---
controller_workflows:
  - name: Z / SETUP / Workshop - CentOS7
    description: Workflow for workshop deployment with CentOS7 nodes
    inventory: Workshop Inventory
    state: present
    organization: Default
    survey_enabled: false
    simplified_workflow_nodes:
      - identifier: Disable transparent huge pages on Satellite
        unified_job_template: Z / SETUP / Disable transparent hugepages
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - Register CentOS7 nodes to Satellite AK CentOS7_Dev
          - Workflow node delay
      - identifier: Setup Cockpit Web Console
        unified_job_template: Z / SETUP / Cockpit - Web Console
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - Extend partition and resize physical volume
      - identifier: Extend partition and resize physical volume
        unified_job_template: UTILITY / Extend partition and resize physical volume
        organization: Default
        limit: centos7,rhel7
        all_parents_must_converge: false
        always_nodes:
          - Register CentOS7 nodes to Satellite AK CentOS7_Dev
          - Workflow node delay
      - identifier: Workflow node delay
        unified_job_template: UTILITY / Workflow node delay
        organization: Default
        all_parents_must_converge: true
        success_nodes:
          - Register RHEL7 nodes to Satellite AK RHEL7_Dev
      - identifier: Register RHEL7 nodes to Satellite AK RHEL7_Dev
        unified_job_template: SERVER / RHEL7 - Register
        organization: Default
        all_parents_must_converge: true
        extra_data:
          PREFIX: node
          env: Dev
        success_nodes:
          - Set instance tags based on Satellite facts
      - identifier: Register CentOS7 nodes to Satellite AK CentOS7_Dev
        unified_job_template: SERVER / CentOS7 - Register
        organization: Default
        all_parents_must_converge: true
        extra_data:
          PREFIX: node
          env: Dev
        success_nodes:
          - Set instance tags based on Satellite facts
      - identifier: Set instance tags based on Satellite facts
        unified_job_template: EC2 / Set instance tags based on Satellite facts
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - RHEL7 Development inventory source
      - identifier: RHEL7 Development inventory source
        unified_job_template: RHEL7 Development
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes:
          - CentOS7 Development inventory source
      - identifier: CentOS7 Development inventory source
        unified_job_template: CentOS7 Development
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes:
          - Setup miscellaneous host configuration
      - identifier: Setup miscellaneous host configuration
        unified_job_template: Z / SETUP / Miscellaneous host config
        organization: Default
        all_parents_must_converge: false
        extra_data:
          dynamic_inventory_group: "aws_ec2"
        success_nodes:
          - Publish Content View 1
      - identifier: Publish Content View 1
        unified_job_template: SATELLITE / RHEL - Publish Content View
        organization: Default
        all_parents_must_converge: false
        extra_data:
          env: Dev
          content_view: RHEL7
        success_nodes:
          - Promote Content View
      - identifier: Promote Content View
        unified_job_template: SATELLITE / RHEL - Promote Content View
        organization: Default
        all_parents_must_converge: false
        extra_data:
          content_view: RHEL7
          current_lifecycle_environment: RHEL7_Dev
          lifecycle_environment: RHEL7_QA
        success_nodes:
          - Publish Content View 2
      - identifier: Publish Content View 2
        unified_job_template: SATELLITE / RHEL - Publish Content View
        organization: Default
        all_parents_must_converge: false
        extra_data:
          env: Dev
          content_view: RHEL7
        success_nodes:
          - EC2 Instance action - stop CentOS7 nodes
      - identifier: EC2 Instance action - stop CentOS7 nodes
        unified_job_template: EC2 / Instance action
        organization: Default
        all_parents_must_converge: false
        extra_data:
          instance_action: stop
          content_view: CentOS7
          stage: Dev
        success_nodes: []

  - name: Z / SETUP / Workshop - OL7
    description: Workflow for workshop deployment with OracleLinux7 nodes
    inventory: Workshop Inventory
    state: present
    organization: Default
    survey_enabled: false
    simplified_workflow_nodes:
      - identifier: Disable transparent huge pages on Satellite
        unified_job_template: Z / SETUP / Disable transparent hugepages
        organization: Default
        all_parents_must_converge: false
        success_nodes: []
...
