---
- name: Install convert2rhel utility
  ansible.builtin.import_role:
    name: infra.convert2rhel.common

- name: Pull katello-ca-consumer package from satellite server and place under /usr/share/convert2rhel/subscription-manager
  ansible.builtin.get_url:
    url: https://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    dest: /usr/share/convert2rhel/subscription-manager/katello-ca-consumer-latest.noarch.rpm
    mode: '0440'
    validate_certs: false

- name: Set delay time via gather_facts
  ansible.builtin.set_fact:
    node_delay_time: "{{ inventory_hostname | regex_replace('^\\D+|\\..*', '') | int *30 }}"
  when: c2r_include_delay

- name: Include delay before starting analysis
  ansible.builtin.command: |
    python3 -c 'import time;time.sleep({{ node_delay_time }})'
  delegate_to: localhost
  connection: local
  when: c2r_include_delay

- name: Generate pre-conversion analysis report
  ansible.builtin.import_role:
    name: infra.convert2rhel.analysis

- name: Uninstall katello-ca-consumer package
  ansible.builtin.yum:
    name: "katello-ca-consumer*"
    state: absent

- name: Include randomized delay before removing content host from Satellite
  ansible.builtin.command: |
    python3 -c 'import time;import random;zzzzz=random.uniform(10.0,30.0);time.sleep(zzzzz);print(zzzzz)'
  delegate_to: localhost
  connection: local
  when: c2r_include_delay

- name: Remove host from Satellite satellite.example.com"
  redhat.satellite.host:
    server_url: "https://satellite.example.com"
    name: "{{ inventory_hostname }}"
    organization: "{{ organization }}"
    state: absent
  delegate_to: localhost
  vars:
    organization: "Default Organization"
    validate_certs: false
...
