---
- name: CentOS system modifications
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Configure CentOS7 systems
      when:
        - "ansible_distribution == 'CentOS'"
        - "ansible_distribution_major_version | int  == 7"
      ansible.builtin.import_tasks: misc_host_config_centos7.yml
...
