---
- name: Query Satellite content hosts detail and provide content facet details
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    login: &login
      server_url: "{{ lookup('env', 'SATELLITE_SERVER_URL') }}"
      username: "{{ lookup('env', 'SATELLITE_USERNAME') }}"
      password: "{{ lookup('env', 'SATELLITE_PASSWORD') }}"
      validate_certs: "{{ lookup('env', 'SATELLITE_VALIDATE_CERTS') }}"

  tasks:
    - name: Retrieve Satellite content hosts details
      redhat.satellite.resource_info:
        <<: *login
        resource: hosts
      register: hosts_resource_info_result

    - name: Display resource_info_results
      ansible.builtin.debug:
        var: resource_info_results
      vars:
        resource_info_results:
          hosts: "{{ hosts_resource_info_result }}"

    - name: List host name plus content details
      ansible.builtin.debug:
        msg:
          - "node name: {{ item }}"
          - "content view: {{ hosts_resource_info_result.hosts.resources | selectattr('name', 'search', item) | map(attribute='content_facet_attributes.content_view.name') | first }}" 
          - "lifecycle environment: {{ hosts_resource_info_result.hosts.resources | selectattr('name', 'search', item) | map(attribute='content_facet_attributes.lifecycle_environment.name') | first }}"
      loop: "{{ groups.dynamic_inventory_group }}"
      when: item in hosts_resource_info_result.hosts.resources | selectattr('name', 'search', 'node*') | map(attribute='name')
...
