---
- hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local

  pre_tasks:
    - name: Controller deployment instrumentation
      ansible.builtin.uri:
        url: https://docs.google.com/forms/d/e/1FAIpQLSdIZ77YpETjEfGOoYlXtMnQiU-6M7QFlb2hJA4ujo25QYb2jw/formResponse
        method: POST
        body: "ifq&entry.1569353616=satellite &entry.498055740={{ lookup('ansible.builtin.env', 'AWX_HOST') }}&sumbit=Submit"
      ignore_errors: true

    # Gather EC2 metadata facts
    - amazon.aws.ec2_metadata_facts:
  
    - ansible.builtin.set_fact:
        workshop_ec2_region: "{{ ansible_ec2_instance_identity_document_region }}"

    - name: Include CentOS7 Convert2RHEL CaC via vars files
      block:
        - name: Include Satellite centos7_c2r CaC via vars files
          ansible.builtin.include_vars:
            dir: config_as_code/satellite/centos7_c2r
          delegate_to: satellite.example.com
          delegate_facts: true
      when: controller_cac_scenario == 'CentOS7_C2R'

    - name: Include RHEL8 CaC via vars files
      block:
        - name: Include Controller rhel_8_inventories CaC via vars files
          ansible.builtin.include_vars:
            dir: config_as_code/controller/rhel_8_inventories
        - name: Include Satellite leapp_7_to_8 CaC via vars files
          ansible.builtin.include_vars:
            dir: config_as_code/satellite/leapp_7_to_8
      when: controller_cac_scenario == 'RHEL8'

    - name: Include RHEL9 CaC via vars files
      block:
        - name: Include Controller rhel_9_inventories CaC via vars files
          ansible.builtin.include_vars:
            dir: config_as_code/controller/rhel_9_inventories
        - name: Include Satellite leapp_8_to_9 CaC via vars files
          ansible.builtin.include_vars:
            dir: config_as_code/satellite/leapp_8_to_9
      when: controller_cac_scenario == 'RHEL9'

  roles:
    - {role: infra.controller_configuration.inventories, when: controller_inventories is defined}
    - {role: infra.controller_configuration.inventory_sources, when: controller_inventory_sources is defined}
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}
    - {role: infra.controller_configuration.workflow_job_templates, when: controller_workflows is defined}
...
