---
- hosts: "{{ HOSTS | default('satellite.example.com') }}"
  connection: local
  gather_facts: false
  vars:
    satellite_validate_certs: true
    async_timeout: 3600
    async_delay: 15

  tasks:
    - name: Satellite deployment instrumentation
      ansible.builtin.uri:
        url: https://docs.google.com/forms/d/e/1FAIpQLSdIZ77YpETjEfGOoYlXtMnQiU-6M7QFlb2hJA4ujo25QYb2jw/formResponse
        method: POST
        body: "ifq&entry.1569353616=smart_mgmt &entry.498055740={{ lookup('ansible.builtin.env', 'AWX_HOST') }}&sumbit=Submit"
      ignore_errors: true

    - name: Check satellite status
      redhat.satellite.status_info:
        validate_certs: "{{ satellite_validate_certs }}"

    - name: Include CentOS7 CONVERT2RHEL Satellite CaC via vars files
      ansible.builtin.include_vars:
        dir: config_as_code/satellite/centos7_c2r
      when: satellite_cac_scenario == 'CENTOS7_to_RHEL7'

    - name: Include Oracle7 CONVERT2RHEL Satellite CaC via vars files
      ansible.builtin.include_vars:
        dir: config_as_code/satellite/ol7_c2r
      when: satellite_cac_scenario == 'ORACLE7_to_RHEL7'

    - name: Include RHEL7 to RHEL8 IPU Satellite CaC via vars files
      ansible.builtin.include_vars:
        dir: config_as_code/satellite/leapp_7_to_8
      when: satellite_cac_scenario == 'RHEL7_to_RHEL8'

    - name: Include RHEL7 to RHEL8 IPU Satellite CaC via vars files
      ansible.builtin.include_vars:
        dir: config_as_code/satellite/leapp_8_to_9
      when: satellite_cac_scenario == 'RHEL8_to_RHEL9'

    - name: Include setup_satellite_infra_subtasks
      ansible.builtin.include_tasks: setup_satellite_infra_subtasks.yml

    - name: Include satellite_repository_sync_subtasks
      ansible.builtin.include_tasks: satellite_repository_sync_subtasks.yml
      when: sync_repository | default(true) | bool

    - name: execute content_views role
      ansible.builtin.import_role:
        name: "content_views"
      delegate_to: localhost
...
